### ISSUE TITLE
Error when running packwerk check

### ISSUE THREAD

**Issue by alejandroechev** [rubyatscale/packwerk-extensions#11]
I am getting the following error when running `packwerk check` with the extensions gem installed:

````
from .../bundler/gems/packwerk-extensions-8b9d373c3f36/lib/packwerk/privacy/checker.rb:7:in `<module:Privacy>'<class:Checker>': uninitialized constant Packwerk::Checker (NameError)

      include Packwerk::Checker
      ....
````

Without the extension `packwerk check` works correctly.

I am probably missing a configuration or some setup but I cant find it in the Readme.

**Comment by alexevanczuk** [comment]
Thanks for filing the issue @alejandroechev !

`packwerk-extensions` is based off of `packwerk` 3, which has not yet been released.
`Packwerk::Checker` is part of packwerk 3.

Until packwerk 3 is officially released, you'll need to build off of `packwerk` `main`:
In your `Gemfile`:
```ruby
gem 'packwerk', github: 'Shopify/packwerk', branch: 'main'
```

Can you give that a try and see if you still have the issue?

**Comment by alejandroechev** [comment]
Thanks @alexevanczuk ! Now it works great :)

Maybe you could add in the Readme some kind of notice warning that there is still no official packwerk version compatible with packwerk-extension and you need to use the Github packwerk. Basically what you just explained to me :)

**Comment by alexevanczuk** [comment]
> Thanks @alexevanczuk ! Now it works great :)
> 
> 
> 
> Maybe you could add in the Readme some kind of notice warning that there is still no official packwerk version compatible with packwerk-extension and you need to use the Github packwerk. Basically what you just explained to me :)

Great point @alejandroechev , I'll add that tomorrow!

Looking forward to hearing any more feedback, thanks again.

**Comment by alejandroechev** [comment]
Thanks for updating the Readme @alexevanczuk !
