### ISSUE TITLE
Improve Opt-In Public Functionality

### ISSUE THREAD

**Issue by aaronmallen** [rubyatscale/packwerk-extensions#36]
Currently packwerk extension offers an opt-in pattern for public constants by putting them in the `app/public` or some other configurable public directory.  This causes a few headaches in that you would either need to have zeitwerk colapse the `app/public` folder or name your constants `MyComponent::Public::MyPublicConstant`.  Packwerk extensions already offers a better opt-out experience with the `private_constants` configuration option.  I would like to see this pattern implemented in the reverse.

Given two components `IdentityProvider` and `GraphApp` and `IdentityProvider` having constants:

* `IdentityProvider::Command::CreateUser`
* `IdentityProvider::Command::FindUserByEmail`
* `IdentityProvider::Command::UpdateUser`

The following would yield:

```yaml
# components/identity_provider/package.yml
enforce_privacy: true
public_constants:
  - IdentityProvider::Command::CreateUser
  - IdentityProvider::Command::UpdateUser
```

```ruby
# components/graph_app/create_user_mutation.rb

module GraphApp
  module Mutation
    class CreateUserMutation < Base
       argument :email, String
       argument :password, String
       argument :password_confirmation, String

       field :user, Type::User

       def resolve(input)
         # This would raise a violation because IdentityProvider::Command::FindUserByEmail is not 
         # listed in the public_constants
         user_exists = IdentityProvider::Command::FindUserByEmail.call(input[:email])
         if user_exists
            # This is allowed because IdentityProvider::Command::UpdateUser is listed in the public_constants
            IdentityProvider::Command::UpdateUser(input)
         else
           # This is allowed because IdentityProvider::Command::CreateUser is listed in the public_constants
           IdentityProvider::Command::CreateUser(input)
         end
       end
    end
  end
end
```

The idea is similar to the `private_constants` feature but instead of opting in to private constants we would assume everything in the component is private unless the constant is opted-in to `public_constants`.

**Comment by alexevanczuk** [comment]
We talked about something similar in https://github.com/rubyatscale/packwerk-extensions/discussions/2, specifically around sigil based public constants. I think it follows a similar idea here, which is that we'd like to have a list of things that are explicitly public (private by default) without using a public folder.

@bschrag620 started doing that in this PR: https://github.com/rubyatscale/packwerk-extensions/pull/35

In order for things not to get confusing, I'm wondering if we can just include one additional way to mark things as public for now and if sigil based promotion would work for you. If not let me know what you think!

An alternative would be to use this pattern *instead* of sigil based promotion to public API. This is certainly simpler to implement and maintain than sigil based promotion (which requires reading the content of files).

cc @ngan

**Comment by shageman** [comment]
@aaronmallen The PR mentioned by @alexevanczuk landed in the latest release of this gem. Check out the [addition to the README](https://github.com/rubyatscale/packwerk-extensions#privacy-checker). Does it solve your issue?

**Comment by aaronmallen** [comment]
Nice this works for me

**Comment by tstannard** [comment]
Closing this issue since it's solved by https://github.com/rubyatscale/packwerk-extensions/pull/35

**Comment by athieriot** [comment]
@alexevanczuk Hello !

We see ourselves considering registering an entire extra directory to the Public paths as well (Use case: Exposing public test helpers to other Engines)

Right now we've started using the sigil but I would like to make it a bit more explicit.

Do you think it's still worth it to try to implement the possibility to accept regular expression in the `public_path` parameter ?
Or does it start to be a bit too many patterns ?

(I'd be happy to implement the change)

**Comment by alexevanczuk** [comment]
Curious what @shageman thinks!

I can see conceptually how we might want the public path to accept a glob to allow arbitrary files to be considered public. Since we just introduced the sigil which is very flexible, it might be worth us continuing to experiment with that and collect more thoughts, maybe as a discussion so other folks can discover and contribute their feedback? What do ya think?
